# Dockerfile
FROM manimcommunity/manim:v0.19.0

RUN apt-get update && apt-get install -y curl gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    node -v && npm -v

WORKDIR /app

COPY execution ./execution/

COPY api/ ./api/
WORKDIR /app/api
RUN npm install


WORKDIR /app/backend
CMD ["node", "server.js"]

